name: Release shaarli2bluesky plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"

      - name: Test
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: intl curl
          command: test

      - name: Remove dev dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          command: update
          args: --no-dev

      - name: Package
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          zip -r shaarli2bluesky.$tag.zip src vendor edit_link.html shaarli2bluesky.{js,css,meta,php}
          tar -czvf shaarli2bluesky.$tag.tar.gz src vendor edit_link.html shaarli2bluesky.{js,css,meta,php}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            shaarli2bluesky.$tag.zip shaarli2bluesky.$tag.tar.gz
